core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.urls.conf import re_path
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('', include('csbok.urls', namespace='csbok')),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT}),
]

#if settings.DEBUG:
 #   urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    #urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

csbok/urls.py
from csbok.models import Category
from django.urls import path

from . import views

app_name = 'csbok'

urlpatterns = [
    path('', views.all_topics, name='all_topics'),
    path('topic/<slug:slug>/', views.topic_detail, name='topic_detail'),
    path('category/<slug:category_slug>/',views.category_list, name='category_list')
]

csbok/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import truncatechars
from django.urls import reverse
from tinymce import models as tinymce_models
import tinymce


class Category(models.Model):
    name = models.CharField( max_length=256, db_index=True)
    slug = models.SlugField( max_length=256, unique=True)

    class Meta:
        verbose_name_plural = 'categories'

    def get_absolute_url(self):
        return reverse('csbok:category_list', args=[self.slug])
    
    def __str__(self):
        return self.name
    
class Topic(models.Model):
    category = models.ForeignKey(Category, related_name='topic',on_delete=models.CASCADE)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='topic_creator')
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=255, default='B.Bhattarai')
    body = tinymce_models.HTMLField()
    media = models.ImageField(upload_to='image/')
    references = models.TextField(blank=False)
    slug = models.SlugField( max_length=256, unique=True)
    created = models.DateField(auto_now_add=True)
    updated = models.DateField(auto_now=True)
    video_link = models.TextField(blank=True)
    abstract = models.TextField(blank=False)

    @property
    def short_body(self):
        return truncatechars(self.body, 50)

    class Meta:
        verbose_name_plural = 'Topics'
        ordering = ('-updated',)
    
    def get_absolute_url(self):
        return reverse('csbok:topic_detail', args=[self.slug])

    def __str__(self):
        return self.title

csbok/views.py
from django.shortcuts import render, get_object_or_404

from .models import Category, Topic

def categories(request):
    return{
        'categories':Category.objects.all()
    }

def all_topics(request):
    topics = Topic.objects.all()
    return render(request, 'csbok/home.html', {'topics':topics})

def topic_detail(request, slug):
    topic = get_object_or_404(Topic, slug=slug)
    return render(request, 'csbok/topics/detail.html', {'topic' : topic})

def category_list(request, category_slug):
    category = get_object_or_404(Category, slug=category_slug)
    topics = Topic.objects.filter(category=category)
    return render(request,'csbok/topics/category.html', {'category' : category, 'topics' : topics})

templates/csbok/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>{% block title %}CSBOK{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-light bg-white border-bottom">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">CSBOK</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
                    aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav me-auto mb-2 mb-md-0">
                        <li class="nav-item active">
                            <a class="nav-link" aria-current="page" href="/">Home</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Module
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="{% url "csbok:all_topics" %}">All</a></li>
                                {% for c in categories %}
                                <li {% if category.slug == c.slug %}class="selected" {% endif %}>
                                    <a class="dropdown-item" href="{{ c.get_absolute_url }}">{{ c.name|title }}</a>
                                </li>
                                {% endfor %}
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div id="content">{% block content %} {% endblock %}</div>
</body>
</html>

templates/csbok/home.html
{% extends "./base.html" %}
{% load static %}
{% block title %}CSBOK{% endblock %}
{% block content %}


<main>

  <div class="album py-5 bg-light">
    <div class="container">

      <div class="pb-3 h5">All Topics</div>
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">

        {% for topic in topics %}

        <div class="col">
          <div class="card shadow-sm">
          <img class="img-fluid mx-auto d-block" width="auto"  alt="Responsive image" src="{{ topic.media.url }}">
            <div class="card-body">
              <p class="card-text">
                <a class="text-dark text-decoration-none" href="{{ topic.get_absolute_url }}">{{ topic.title }}</a>
              </p>
              <div class="d-flex justify-content-between align-items-center">
              </div>
            </div>
          </div>
        </div>

        {% endfor %}

      </div>
    </div>
  </div>


</main>


{% endblock %}

templates/csbok/topics/category.html
{% extends "../base.html" %}
{% load static %}
{% block title %}{{ category.name }}{% endblock %}
{% block content %}


<main>

  <div class="album py-5 bg-light">
    <div class="container">

      <div class="pb-3 h5">{{ category.name }}</div>
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">

        {% for topic in topics %}

        <div class="col">
          <div class="card shadow-sm">
            <img class="img-fluid" alt="Responsive image" src="{{ topic.media.url }}">
            <div class="card-body">
              <p class="card-text">
                <a class="text-dark text-decoration-none" href="{{ topic.get_absolute_url }}">{{ topic.title }}</a>
              </p>
              <div class="d-flex justify-content-between align-items-center">
              </div>
            </div>
          </div>
        </div>

        {% endfor %}

      </div>
    </div>
  </div>


</main>


{% endblock %}

templates/csbok/topics/detail.html
{% extends "../base.html" %}
{% load static %}
{% block title %}{{ topic.title }}{% endblock %}
{% block content %}


<div class="container">
    <main class="pt-5">
        <div class="row g-3">
            <div class="col-md-5 col-lg-5 order-md-first bg-light">
                <img class="img-fluid mx-auto d-block" width="auto"  alt="Responsive image" src="{{ topic.media.url }}">
            </div>
            <div class="col-md-7 col-lg-7 ps-md-3 ps-lg-5">
                <h1 class="mb-0 h4">{{ topic.title }}</h1>
                <p><span class="lead">{{ topic.author }}</span> (Author)</p>
                <p>Category: {{ topic.category }}</p>
                <div class="text-muted"><p>{{ topic.abstract }}</p></div>
                <div class="col">
                        <div class="row p-3">
                            <div class="col-6 text-muted">
                            Created on: {{ topic.created }}
                            </div>
                            <div class="col-6 text-muted">
                            Updated at: {{ topic.updated }}
                            </div>
                        </div>
                    </div>
                <div class="border">
                    <div class="col border-bottom">
                        <div class="row p-3">
                            <div>Video link with explanation for the topic:</div>
                        </div>
                    </div>
                    <div class="col">
                        <div class="row p-3">
                                <a class="text-primary text-decoration-none" href="{{ topic.video_link }}">{{ topic.video_link }}</a>
                        </div>
                    </div>
                </div>
            </div>
            {% autoescape on %}
            <p>{{ topic.body|safe}}</p>
            {% endautoescape %}
            
        </div>
    </main>

</div>


{% endblock %}